version: '2.2'
services:
  api:
    build:
      context: docker/dockerfile/api
    working_dir: /app
    expose:
      - 3000
    volumes:
      - $PWD:/app
    networks:
      - main
    environment:
      - "NPM_REGISTRY=https://registry.npmjs.org"
    command:  sh -c "npm install; npm start"
    restart: "always"

  tor:
    image: docker.loc:5000/dperson/torproxy
    environment:
      - "EXITNODE={us} StrictNodes 1"
    networks:
      - main
    restart: "always"

  ssh-proxy:
    image: docker.loc:5000/ssh-proxy/client:1.0.0
#    environment:
#      - "REMOTE_PORT=$REMOTE_PORT"
#      - "REMOTE_HOST=$REMOTE_HOST"
#      - "REMOTE_USERNAME=$REMOTE_USERNAME"
#      - "SSH_TUNNEL_PORT=$SSH_TUNNEL_PORT"
#      - "USER_SSH_PRIVATE_KEY=$USER_SSH_PRIVATE_KEY"
    networks:
      - main
    restart: "always"

  download:
    image: docker.loc:5000/httpd:2.4-alpine
    volumes:
      - $PWD/storage/download:/usr/local/apache2/htdocs/download
    networks:
      - main
    restart: "always"

networks:
  main:
