version: '2.2'
services:
  mongo:
    image: docker.loc:5000/mongo:3
    volumes:
      - mongo-storage:/etc/mongo
      - mongo-data-storage:/data/db
    command: "--smallfiles"
    networks:
      main:
        aliases:
          - db

  chat:
    image: docker.loc:5000/rocket.chat:0.74
    networks:
      - main
    ports:
      - 3003:3000

  api:
    dns:
      - 192.168.1.217
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - "NODE_ENV="
    ports:
      - 3001:3000
    command: sh -c "npm install; npm run nodemon"

volumes:
  mongo-storage:
  mongo-data-storage:
